### ISSUE TITLE
Dicionário de dados

### ISSUE THREAD

**Issue by kailanyas** [KesavaS2/avanti-bootcamp-cdd#2]
- [x] Realizar coleta inicial de dados, seja ela através de download ou criação de script para download automático dos dados. Você deverá criar um arquivo com os dados e colocá-lo na pasta `data/raw.`
- [x] Criar dicionário de dados, uma estrutura que servirá para explicar o dado que será trabalhado. Você poderá criar um dicionário python contendo as seguintes informações para cada uma das variáveis do conjunto de dados:
- variavel: nome da coluna no pandas
- descricao: descrição da coluna
- tipo: quantitativa ou qualitativa
- subtipo: nominal, ordinal, discreta, contínua

**Comment by kailanyas** [comment]
Acredito que o subtipo da variável _age_ está incorreto. Fora isso, o dicionário está ótimo, parabéns!

**Comment by KesavaS2** [comment]
> Acredito que o subtipo da variável _idade_ está incorreto. Fora isso, o dicionário é ótimo, parabéns!

Irei rever!

**Comment by KesavaS2** [comment]
> Acredito que o subtipo da variável _age_ está incorreto. Fora isso, o dicionário está ótimo, parabéns!

O subtipo da variável "age" pode ser considerada contínuo, pois ela inclui valores com casas decimais, tanto para idades menores que um ano, contadas em meses, quanto para idades com decimais, como por exemplo, 23,5 anos. Isso significa que a variável pode assumir qualquer valor dentro de um intervalo, sem ser limitada a números inteiros. Portanto, tratar essa variável como contínua permite-se representar melhor a realidade dos dados.

**Comment by kailanyas** [comment]
Certo!
Então seu dicionário de dados está ótimo! :)
